development:
    secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
test:
    secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
staging:
    secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
production:
    secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
